### ISSUE TITLE
Construction and trees aren't being counted in designated areas.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#10]
Not sure if regular bed are also affected, but room seems to sometimes ignore beds.
EDIT
It's more area related issue, because trees aren't being counted in groves too.

**Comment by rschurade** [comment]
Trees in groves and this are totally unrelated issues. Lets focus on the beds. I see in the 146 save game that some beds are registered and some are not. So it would be interesting what is different between them.

**Comment by rschurade** [comment]
Ok the reason the beds don't show up in the room window is because the items don't exist anymore. The rooms and the construction list correctly contain an entry but the items list doesn't contain the item any more. That causes the room window to not show the item. Now when constructing a bed or any furniture they should just get the "constructed" flag and not be destroyed.

**Comment by lokkiser** [comment]
I also noticed, that sometimes instead of barrels i get installed beds. And they are counted as correct beds to sleep.
