### ISSUE TITLE
Items crafted from wrong materials

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#23]
I just noticed that i have several items crafted from the wrong materials (pine).

I have a pine bar, pine mattress, pine bolt of cloth and I can craft additional pine mattresses because I have the pine bolt of clothes.

I can't order my loom to craft additional pine bolts, though.

![image](https://user-images.githubusercontent.com/50493006/61593153-d1ee1100-abd3-11e9-8677-01e11b094430.png)

**Comment by rschurade** [comment]
That's a duplicate of #9 and a pretty serious issue but I can't reproduce it or find a reason.

**Comment by rschurade** [comment]
To further clarify being able to craft a pine mattress is totally ok. There is no check for material it just takes a bolt of cloth. There shouldn't be a pine bolt of cloth because that is made from raw cloth which is only produced from sheep or cotton plants. 

I can see one possible place where the error happens and added another reset of claimed items at job start.

**Comment by Daxtgnomoria** [comment]
Haven't seen it again after recent patches.
