### ISSUE TITLE
Crafting sandwich is inefficient (food points)

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#24]
I know food is still a work in progress and balancing it will take time, but I just wanted to share my thoughts on sandwiches.

Crafting a sandwich is "inefficient", since you lose food value in the process. A bread is worth 30 points and sausage is also worth 30 points. However, making a sandwich costs labor+bread+sausage and is only worth 50 points (less than the ingredients, plus you waste the labor). Since you are not wasting any resources when crafting a sandwich (from the realistic point of view), I think sandwiches should be worth at least 60 points.

I know you can save some time for the eating gnome, because you are eating more food points/item, and save trips to the kitchen (because with sandwich you are going to stack more food above the 100 hunger level, but since it is the current top grade food and takes more labor than omelettes, I think it should offer more benefits.

In this sense, from the food value efficient point of view, I think it is better to just let them eat the bread and the sausage separately.

Any thoughts on that?  Would you prefer if I moved this discussion to reddit, so more people can comment?

**Comment by rschurade** [comment]
Ah finally not a bug

**Comment by rschurade** [comment]
The idea is indeed that it saves time by spending less time eating so the total value doesn't need to be  bread+sausage. There is also the possibility that higher skill produces better quality sandwiches later and those have higher food value. Also instead of raising the value of the sandwich we might lower the values of bread and sausage. This is a matter of balancing which will surely take some iteration to get it right. Feel free to make that a reddit thread if you want.

**Comment by Daxtgnomoria** [comment]
I like the idea of higher quality food having higher food value!

I thought that the reason for this food amount was related to time saving. For now I think it is too early to talk about balancing food, considering that more foods are to come (i imagine) and that other features are going to change how food points works!

Lets close it for now and on a later time we can discuss that on reddit.
