### ISSUE TITLE
Invalid Markup for XAML UI

### ISSUE THREAD

**Issue by jiri-otoupal** [rschurade/Ingnomia#59]
Hi, 
i had encountered erros for XAML part of Ingnomia 
![obrazek](https://user-images.githubusercontent.com/69390758/90071544-0c9e7c00-dcf6-11ea-86e8-c8ff864a5ffb.png)

How to solve it so i can edit it in frame ?

**Comment by Ext3h** [comment]
You have to *build* the `gui` project *first*, before Blend starts working.

In order to build the project, you will need to open it outside the solution, or toggle a value in Solution->Properties->Configuration Properties->gui->Configuration. If you don't do that, the build will be "skipped" due to a bug in Visual Studio.

**Comment by jiri-otoupal** [comment]
I got it working :) thanks
