### ISSUE TITLE
transparency/glow effects broken

### ISSUE THREAD

**Issue by rschurade** [rschurade/Ingnomia#66]
Transparency doesn't work currently due to renderer limitations. Tile including transparent sprites need an extra flag.

**Comment by Ext3h** [comment]
Tiles which contain semi-transparency and/or abnormal bounding boxes need to be flagged as such so they can be dealt with during rendering.

Tiles flagged with semi-transparency must be skipped from the first rendering pass, and be moved to the second one together with water etc. 

Tiles flagged as "oversized" need a different bounding box during rendering.

Both flags need to be use sparingly though, as they came at a significant overhead due to overdraw.
